name: Tests 🎳

on:
  push:
#    paths:
#      - '**.php'
  pull_request:
#    paths:
#      - '**.php'
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: PHP-CS-Fixer
      uses: docker://oskarstark/php-cs-fixer-ga
      with:
        args: --config=.php-cs-fixer.dist.php --diff --dry-run
  phpstan:
    name: "Php-Stan"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Get composer cache directory
      id: get-composer-cache-dir
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: phpstan

    - name: Cache dependencies
      uses: actions/cache@v2.1.7
      with:
        path: ${{ steps.get-composer-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest && git clone https://github.com/3liz/lizmap-web-client.git
    - name: PHPStan version
      run: phpstan -V

    - name: Run PHPStan
      run: phpstan analyse -c phpstan.neon
